name: Auto Update Free Nodes

on:
  schedule:
    - cron: "0 * * * *"  # 每小時執行一次（UTC 時區）
  workflow_dispatch:       # 允許手動觸發

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run fetch script
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add nodes.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Update nodes $(date -u '+%Y-%m-%d %H:%M:%S')"
        git push
